---
title: "Artigo - Aplicação"
subtitle: "Modelagem com Apoio Computacional"
author: "Tailine J. S. Nonato"
date: today
date-format: long
format: html
---

# Pacotes
```{r}
#| label: pacotes

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, knitr, MASS, maxLik, VGAM, miscTools, rmarkdown)
```

# Log-verossimilhança e critérios de informação (padronizado)

```{r}
#| label: fun_ic

## Todas as funções de ajuste abaixo devem fornecer a log-verossimilhança
## MAXIMIZADA (logLik, valor positivo na escala usual) e o número de
## parâmetros do modelo (npar). Este é o único ponto do código que calcula
## AIC/BIC, evitando divergências de convenção de sinal entre os modelos.
compute_ic <- function(logLik, npar, n) {
  aic <- -2 * logLik + 2 * npar
  bic <- -2 * logLik + npar * log(n)
  list(AIC = aic, BIC = bic)
}
```

# Média
```{r}
#| label: fun_media

#########################################################
## Regression by Rieck and Nedelman (1991)
## Rieck, J.R., Nedelman, J.R., 1991. A log-linear model for the
## Birnbaum–Saunders distribution. Technometrics 33, 51–60.
#########################################################

mle_unc <- function(x, t, v, kernel = "normal") {
  x <- as.matrix(x)
  t <- as.matrix(t)
  y <- as.matrix(log(t))
  fit <- lm.fit(x, y)
  beta <- c(fit$coef)
  k <- length(beta)
  n <- length(y)
  mu <- x %*% beta
  alpha <- sqrt((4 / n) * sum((sinh((y - mu) / 2)) ^ 2))
  thetaStar <- c(beta, alpha)
  # loglik() retorna a NEGATIVA da log-verossimilhança (minimizada pelo optim)
  loglik <- function(par) {
    z1 <- par[1:k]
    z2 <- par[k + 1]
    mu <- (x %*% z1)
    xi1 <- (2 / z2) * cosh((y - mu) / 2)
    xi2 <- (2 / z2) * sinh((y - mu) / 2)
    g <- switch(kernel,
      "normal" = exp(-(xi2 ^ 2) / 2),
      "t" = (v + (xi2 ^ 2)) ^ (-(v + 1) / 2)
    )
    const <- switch(kernel,
      "normal" = 1 / (sqrt(2 * pi)),
      "t" = (gamma((v + 1) / 2) * v ^ (v / 2)) /
        (sqrt(pi) * gamma(v / 2))
    )
    result <- switch(kernel,
      "normal" = sum(log(const / 2) + log(xi1) + log(g)),
      "t" = sum(log(const / 2) + log(xi1) + log(g))
    )
    return(-result)
  }
  loglikplus <- function(par) {
    z1 <- par[1:k]
    z2 <- par[k + 1]
    mu <- (x %*% z1)
    xi1 <- (2 / z2) * cosh((y - mu) / 2)
    xi2 <- (2 / z2) * sinh((y - mu) / 2)
    result <- log(dnorm(xi2)) + log(xi1 / 2)
    return(sum(result))
  }
  est <- optim(thetaStar, loglik, method = "BFGS", hessian = TRUE)
  if (est$conv != 0)
    warning("FUNCTION DID NOT CONVERGE!")
  coef <- (est$par)[1:k]
  alphaest <- est$par[k + 1]
  muhat <- x %*% coef
  muhat <- as.vector(muhat)
  etahat <- exp(muhat)
  SHess <- solve(est$hessian)
  SE <- sqrt(diag(SHess))
  se.coef <- SE
  tval <- c(coef, alphaest) / se.coef
  matcoef <- cbind(c(coef, alphaest), se.coef, tval, 2 * (1 - pnorm(abs(tval))))
  colnames(matcoef) <- c("Estimate", "Std. Error", "t value", "Pr(>|t|)")
  rownames(matcoef) <- c(paste0("beta", 0:(k - 1)), "alpha")

  # log-verossimilhança MAXIMIZADA (positiva) e critérios de informação padronizados
  logLikValue <- -loglik(c(coef, alphaest))
  ic <- compute_ic(logLikValue, npar = k + 1, n = n)

  out <- list(
    par = est$par,
    beta = coef,
    alpha = alphaest,
    se = se.coef,
    muHat = muhat,
    etaHat = etahat,
    value = est$value,
    hessian = est$hessian,
    convergence = est$convergence,
    matcoef = matcoef,
    logLik = logLikValue,
    AIC = ic$AIC,
    BIC = ic$BIC,
    n = n
  )
  class(out) <- "mle_media"
  return(out)
}
```

# Moda

```{r}
#| label: fun_moda
###############################################################
## Reparametrização da distribuição Birnbaum-Saunders pela moda.
##
## O parâmetro mu representa a MODA da distribuição.
##
## Internamente, a densidade é escrita utilizando o parâmetro
## de escala beta da BS clássica, obtido por
##
##      beta = mu / (1 - phi)
##
## onde
##
##      phi = alpha^2
##
## Assim, a modelagem é realizada sobre a moda (mu), enquanto
## beta é apenas um parâmetro auxiliar necessário para escrever
## a densidade da Birnbaum-Saunders.
###############################################################

dbsmoda_logpdf <- function(y, mu, phi) {
  alpha <- sqrt(phi)
  beta  <- mu / (1 - phi)
  log_pdf <- -0.5*log(2*pi) - log(2*alpha*sqrt(beta)) - 1.5*log(y) + log(y + beta) -
    ( (y/beta) + (beta/y) - 2 ) / (2*alpha^2)
  as.vector(log_pdf)
}

dbsmoda <- function(t, mu, phi, log = FALSE) {
  lp <- dbsmoda_logpdf(t, mu, phi)
  if (log) return(lp)
  exp(lp)
}

mle_dbsmoda <- function(x, z, t){
  x <- as.matrix(x)
  z <- as.matrix(z)
  y <- as.vector(t)
  k <- ncol(x)
  l <- ncol(z)
  n <- length(y)

  # loglik() retorna a NEGATIVA da log-verossimilhança (minimizada pelo optim)
  loglik <- function(par){
    nu <- par[1:k]
    xi <- par[(k + 1):(k + l)]
    eta_mu  <- as.vector(x %*% nu)
    eta_phi <- as.vector(z %*% xi)
    mu  <- exp(eta_mu)
    phi <- plogis(eta_phi)
    -sum(dbsmoda_logpdf(y, mu, phi))
  }

  theta0 <- rep(0, k + l)  # chute neutro
  est <- optim(theta0, loglik, method = "BFGS", hessian = TRUE,
               control = list(reltol = 1e-9, maxit = 1000))

  nu  <- as.vector(est$par[1:k])
  xi  <- as.vector(est$par[(k + 1):(k + l)])

  # erros-padrão
  se <- sqrt(diag(solve(est$hessian)))

  zstatnu   <- nu / se[1:k]
  zstatxi   <- xi / se[(k + 1):(k + l)]
  pvalornu  <- 2 * pnorm(abs(zstatnu), lower.tail = FALSE)
  pvalorxi  <- 2 * pnorm(abs(zstatxi), lower.tail = FALSE)

  names(nu) <- colnames(x)
  names(xi) <- colnames(z)

  senu <- se[1:k]
  sexi <- se[(k + 1):(k + l)]

  tb_mu  <- miscTools::coefTable(nu, senu, df = (n - (k + l)))
  tb_phi <- miscTools::coefTable(xi, sexi, df = (n - (k + l)))

  muHat  <- exp(as.vector(x %*% nu))
  phiHat <- plogis(as.vector(z %*% xi))

  # log-verossimilhança MAXIMIZADA (positiva) e critérios de informação padronizados
  logLikValue <- -loglik(est$par)
  ic <- compute_ic(logLikValue, npar = k + l, n = n)

  out <- list(
    par         = est$par,
    beta_nu     = nu,
    beta_xi     = xi,
    se          = se,
    muHat       = muHat,
    phiHat      = phiHat,
    value       = est$value,
    hessian     = est$hessian,
    convergence = est$convergence,
    tables      = list(mu = tb_mu, phi = tb_phi),
    logLik      = logLikValue,
    AIC         = ic$AIC,
    BIC         = ic$BIC,
    n           = n
  )
  class(out) <- "mle_dbsmoda"
  out
}
```


# Quantis

```{r}
#| label: fun_quantis


#revised function by T. Nonato
#authors: L. Sanchez, V. Leiva
#source: https://doi.org/10.1002/asmb.2556

bsreg.fit <- function(x, y, q = 0.5, link = "log"){
  n <- NROW(x)
  p <- NCOL(x)
  linkobj <- make.link(link)
  linkfun <- linkobj$linkfun
  linkinv <- linkobj$linkinv
  Q.eta <- linkobj$mu.eta
  ystar <- linkfun(y)
  beta <- ginv(t(x) %*% x) %*% t(x) %*% ystar

  xbar <- mean(y)
  vart <- (n/(n-1))*var(y)
  r <- vart / xbar^2
  alphai <- sqrt((2*r-2+2*sqrt(1+3*r))/(5-r))

  if (is.nan(alphai) || is.na(alphai)) {
    s1 <- mean(y)
    r1 <- 1/mean(1/y)
    alphai <- sqrt(2*sqrt(s1/r1)-2)
  }

  start <- c(as.vector(beta), alphai)

  # função de log-verossimilhança (valor MAXIMIZADO, positivo)
  fr <- function(vp) {
    betab <- vp[1:p]
    eta <- as.vector(x %*% betab)
    Q <- linkinv(eta)
    alphab <- vp[p+1]
    zq <- qnorm(q, mean = 0, sd = 1)
    gma_alphab <- alphab * zq + sqrt(alphab^2 * zq^2 + 4)
    vt <- y
    sum(-0.5*log(8*pi*vt) - log(alphab) - log(gma_alphab) - 0.5*log(Q) +
        log(gma_alphab^2/2 + 2*Q/vt) -
        (2*Q/(alphab^2*gma_alphab^2*vt))*(vt*gma_alphab^2/(4*Q) - 1)^2)
  }

  # função gradiente: retorna um vetor NUMÉRICO de comprimento p+1
  grr <- function(vp) {
    betab <- vp[1:p]
    eta <- as.vector(x %*% betab)
    Q <- linkinv(eta)
    alphab <- vp[p+1]
    zq <- qnorm(q)
    gma_alphab <- alphab * zq + sqrt(alphab^2 * zq^2 + 4)
    # derivadas auxiliares
    gma_alphabp <- zq + zq^2 * alphab * (1 / sqrt(alphab^2 * zq^2 + 4))
    vt <- y
    z <- -0.5*(1/Q) - 2*(1/(alphab^2 * gma_alphab^2 * vt)) +
         gma_alphab^2 * vt * (1/(8 * alphab^2 * Q^2)) +
         4*(1/(vt * gma_alphab^2 + 4*Q))

    b <- -(gma_alphab + alphab * gma_alphabp) * (1/(alphab * gma_alphab)) +
         2*vt * gma_alphab * gma_alphabp * (1/(vt * gma_alphab^2 + 4*Q)) -
         (gma_alphab * gma_alphabp * alphab - gma_alphab^2) * vt * (1/(4*Q*alphab^3)) -
         2*(1/(alphab^3)) +
         4*Q*(gma_alphab + alphab * gma_alphabp) * (1/(alphab^3 * gma_alphab^3 * vt))

    # gradiente em relação a beta (p x 1)
    grad_beta <- as.vector(t(x) %*% (Q.eta(eta) * z))
    # gradiente em relação a alpha (escalar)
    grad_alpha <- sum(b)

    c(grad_beta, grad_alpha)
  }

  A <- matrix(c(rep(0,p),1),1,p+1)
  B <- 0

  opt <- maxLik::maxBFGS(fn = fr, grad = grr, start = start,
                         constraints = list(ineqA = A, ineqB = B))

  if (!is.null(opt$code) && opt$code > 0) warning("optimization failed to converge (opt$code > 0)")
  if (!is.null(opt$convergence) && opt$convergence != 0) warning("optimizer signaled non-zero convergence code")

  estimates <- opt$estimate

  # log-verossimilhança MAXIMIZADA (positiva) e critérios de informação padronizados
  logLikValue <- if (!is.null(opt$maximum)) opt$maximum else NA
  ic <- compute_ic(logLikValue, npar = p + 1, n = n)
  AICc <- ic$AIC + (2 * (p + 1) * ((p + 1) + 1)) / (n - (p + 1) - 1)

  beta <- as.vector(estimates[1:p])
  eta <- as.vector(x %*% beta)
  Q <- linkinv(eta)
  alpha <- estimates[p+1]
  zq <- qnorm(q, mean = 0, sd = 1)

  aux <- matrix(1, ncol = 1L, nrow = n)

  gma_alpha <- alpha * zq + sqrt(alpha^2 * zq^2+4)
  gma_alphap <- zq+alpha*zq^2*(1/sqrt(alpha^2*zq^2+4))
  gma_alphapp <- 4*zq^2*(1/sqrt(alpha^2*zq^2+4)^3)

  par_alpha <- alpha
  par_beta  <- 4*Q/gma_alpha^2

  Acal <- ((2*gma_alphap+alpha*gma_alphapp)*(alpha*gma_alpha)-(gma_alpha+alpha*gma_alphap)^2)/
          (alpha^2*gma_alpha^2)
  Bcal <- 8*Q*(gma_alphap^2+gma_alpha*gma_alphapp)
  Ccal <- (1/(4*Q*alpha^4))*(alpha^2*gma_alphap^2+alpha^2*gma_alpha*gma_alphapp-alpha*gma_alpha*gma_alphap-
          3*gma_alpha*gma_alphap*alpha+3*gma_alpha^3)
  Dcal <- 4*Q*((2*gma_alphap+alpha*gma_alphapp)*alpha*gma_alpha-3*(gma_alpha+alpha*gma_alphap)^2)/
          (alpha^4*gma_alpha^4)

  if(link == "log"){
      a <- Q
      h1 <- Q^2
      h2 <- -1/(Q^2*(log(Q)^3))}

  if(link == "identity"){
      a <- rep(1,n)
      h1 <- 1
      h2 <- 0}

  if(link == "sqrt"){
      a <- 2*sqrt(Q)
      h1 <- 4*Q
      h2 <- -1/(4*Q^3)}

    integ.f2 <- c()
    integ.f3 <- c()
    integ.f4 <- c()
    integ.f5 <- c()

  f2 <- function(u,j){
      return((u/(u*gma_alpha^2+4*Q[j]))^2*dbisa(u, par_beta[j], par_alpha))}

  f3 <- function(u,j){
      return((u/(u*gma_alpha^2+4*Q[j])^2)*dbisa(u, par_beta[j], par_alpha))}

  f4 <- function(u,j){
      return((1/(u*gma_alpha^2+4*Q[j])^2)*dbisa(u, par_beta[j], par_alpha))}

  f5 <- function(u,j){
    return((1/(u*gma_alpha^2+4*Q[j]))*dbisa(u, par_beta[j], par_alpha))}

  # tenta integrar; se der erro, retorna 0
  safe_integrate <- function(fun, j, lower = 1e-6, upper = 1000) {
    val <- tryCatch(
      integrate(fun, lower = lower, upper = upper, j = j)$value,
      error = function(e) NA_real_)
    if (is.na(val) || is.infinite(val)) val <- 0
    return(val)}

  for (i in seq_len(n)) {
    integ.f2[i] <- safe_integrate(f2, i)
    integ.f3[i] <- safe_integrate(f3, i)
    integ.f4[i] <- safe_integrate(f4, i)
    integ.f5[i] <- safe_integrate(f5, i)
  }

  v <- (-1/(2*Q^2)+16*integ.f4 + (1/(alpha^2*Q^2))*(1+alpha^2/2))*h1-
      (1/(2*Q)+(1/(2*alpha^2*Q))*(1+alpha^2/2)-4*integ.f5)*h2

  s <- 8*gma_alpha*gma_alphap*integ.f3 -
      ((gma_alpha * gma_alphap * alpha- gma_alpha^2)/(alpha^3*gma_alpha^2*Q^2))*(1+alpha^2/2)-
      ((gma_alpha +alpha* gma_alphap)/(alpha^3*gma_alpha *Q))*(1+alpha^2/2)

  u <- Acal-Bcal*integ.f3 -2*(gma_alpha^3*gma_alphapp-gma_alpha^2*gma_alphap^2)^2*
      integ.f2 + Ccal*(4*Q/gma_alpha^2)*(1+alpha^2/2)-6/alpha^4-
      Dcal*(gma_alpha^2/(4*Q))*(1+alpha^2/2)

  kbb <- t(x)%*%diag(as.vector(v))%*%x
  kaa <- sum(diag(as.vector(u)))
  kba <- t(x)%*%diag(as.vector(a))%*%s

  Diag <- function(A){
    diag.A <- vector()
    for(t in 1:ncol(A)){
      diag.A[t] = A[t,t]
    }
    return(as.vector(diag.A))
  }

  fisher <- cbind(rbind(kbb, t(kba)), rbind(kba, kaa))
  se  <- sqrt(Diag(solve(fisher)))

  hess <- as.matrix(opt$hessian)

  if(p == 1) {
    var.explic <- x
  }  else {
            var.explic <- x[,-1]
          }

  zstatbeta <- beta / se[1:p]
  zstatalpha <- alpha / se[p+1]
  pvalorbeta <- 2 * pnorm(abs(zstatbeta), lower.tail = F)
  pvaloralpha <- 2 * pnorm(abs(zstatalpha), lower.tail = F)

  names(beta) <- colnames(x)

  out <- list(
    coefficients = list(beta = beta, alpha = alpha),
    se = se,
    zstat = list(beta = zstatbeta, alpha = zstatalpha),
    pvalor = list(beta = pvalorbeta, alpha = pvaloralpha),
    logLik = logLikValue,
    AIC = ic$AIC,
    BIC = ic$BIC,
    AICc = AICc,
    hessian = hess,
    n = n
  )
  class(out) <- "bsreg.fit"
  return(out)
}
```

# Tabela de resultados em LaTeX

```{r}
#| label: fun_tabela_latex

## Função separada, chamada explicitamente, para gerar as tabelas de
## resultados (coeficientes e critérios de seleção) em formato LaTeX.
## Recebe uma lista nomeada de modelos ajustados (mle_media, mle_dbsmoda
## ou bsreg.fit) e devolve os códigos LaTeX das tabelas.
gerar_tabela_latex <- function(modelos, digits = 3) {

extrai_coefs <- function(nome, fit) {

  if (inherits(fit, "mle_media")) {

    m <- fit$matcoef

    data.frame(
      Modelo      = nome,
      Parametro   = rownames(m),
      Estimativa  = m[, "Estimate"],
      "Erro Padrao" = m[, "Std. Error"],
      "Wald"      = m[, "t value"],
      "p-valor"   = m[, "Pr(>|t|)"],
      check.names = FALSE
    )

  } else if (inherits(fit, "mle_dbsmoda")) {

    tb_mu  <- fit$tables$mu
    tb_phi <- fit$tables$phi

    rbind(

      data.frame(
        Modelo      = nome,
        Parametro   = paste0("mu_", rownames(tb_mu)),
        Estimativa  = tb_mu[, "Estimate"],
        "Erro Padrao" = tb_mu[, "Std. Error"],
        "Wald"      = tb_mu[, "t value"],
        "p-valor"   = tb_mu[, "Pr(>|t|)"],
        check.names = FALSE
      ),

      data.frame(
        Modelo      = nome,
        Parametro   = paste0("phi_", rownames(tb_phi)),
        Estimativa  = tb_phi[, "Estimate"],
        "Erro Padrao" = tb_phi[, "Std. Error"],
        "Wald"      = tb_phi[, "t value"],
        "p-valor"   = tb_phi[, "Pr(>|t|)"],
        check.names = FALSE
      )
    )

  } else if (inherits(fit, "bsreg.fit")) {

    beta  <- fit$coefficients$beta
    alpha <- fit$coefficients$alpha
    se    <- fit$se

    data.frame(
      Modelo      = nome,
      Parametro   = c(names(beta), "alpha"),
      Estimativa  = c(beta, alpha),
      "Erro Padrao" = se,
      "Wald"      = c(fit$zstat$beta,
                      fit$zstat$alpha),
      "p-valor"   = c(fit$pvalor$beta,
                      fit$pvalor$alpha),
      check.names = FALSE
    )

  } else {

    stop("Classe de modelo nao suportada: ",
         paste(class(fit), collapse="/"))

  }
}
  tab_coef <- do.call(rbind, Map(extrai_coefs, names(modelos), modelos))
  rownames(tab_coef) <- NULL
  tab_coef[, c("Estimativa", "Erro Padrao", "Wald", "p-valor")] <-
    round(tab_coef[, c("Estimativa", "Erro Padrao", "Wald", "p-valor")], digits)

  tab_criterios <- data.frame(
    Modelo = names(modelos),
    logLik = round(sapply(modelos, function(f) f$logLik), digits),
    AIC    = round(sapply(modelos, function(f) f$AIC), digits),
    BIC    = round(sapply(modelos, function(f) f$BIC), digits)
  )

  list(
    coeficientes = knitr::kable(
      tab_coef, format = "latex", booktabs = TRUE, row.names = FALSE,
      caption = "Estimativas dos modelos ajustados."
    ),
    criterios = knitr::kable(
      tab_criterios, format = "latex", booktabs = TRUE, row.names = FALSE,
      caption = "Log-verossimilhanca e criterios de selecao dos modelos."
    ),
    tab_coef = tab_coef,
    tab_criterios = tab_criterios
  )
}
```


# Aplicação

```{r}
#| label: dados

castor <- read.csv2("C:\\Users\\07391760137\\Downloads\\Outros\\MSc-est\\SINAPE\\castorseed.csv")

#phase="Germinated"
castor <- castor %>%
  filter(phase == "Germinated")


# Média
mle_media <- mle_unc(x=model.matrix(~ temperature + puncture + time_under_hydration, data=castor),
                     t=castor$time)
betahat_media <- mle_media$beta
alphahat_media <- mle_media$alpha

# Moda
mle_moda <- mle_dbsmoda(x=model.matrix(~ temperature + puncture + time_under_hydration, data=castor),
                         z=matrix(1, nrow=nrow(castor), ncol=1),
                         t=castor$time)
betahat_moda <- mle_moda$beta_nu
alphahat_moda <- mle_moda$beta_xi

# Quantis
mle_quantil_10 <- bsreg.fit(x=model.matrix(~temperature + puncture + time_under_hydration, data=castor),
                          y=castor$time, q=0.1, link = "log")
betahat_quantil_10 <- mle_quantil_10$coefficients$beta
alphahat_quantil_10 <- mle_quantil_10$coefficients$alpha

# Mediana
mle_mediana <- bsreg.fit(x=model.matrix(~temperature + puncture + time_under_hydration, data=castor),
                          y=castor$time, q=0.5, link = "log")
betahat_mediana <- mle_mediana$coefficients$beta
alphahat_mediana <- mle_mediana$coefficients$alpha

mle_quantil_90 <- bsreg.fit(x=model.matrix(~temperature + puncture + time_under_hydration, data=castor),
                          y=castor$time, q=0.9, link = "log")
betahat_quantil_90 <- mle_quantil_90$coefficients$beta
alphahat_quantil_90 <- mle_quantil_90$coefficients$alpha

# A tabela de resultados (coeficientes + AIC/BIC/logLik) e gerada
# explicitamente aqui, chamando a função separada:
modelos <- list(
  "Media"      = mle_media,
  "Moda"       = mle_moda,
  "Quantil 10" = mle_quantil_10,
  "Mediana"    = mle_mediana,
  "Quantil 90" = mle_quantil_90
)
tabelas_latex <- gerar_tabela_latex(modelos)
tabelas_latex$coeficientes
tabelas_latex$criterios
```

```{r}
extract_results <- function(fit){

  if(inherits(fit,"mle_media")){

    tb <- fit$matcoef

    out <- data.frame(
      Parameter = rownames(tb),
      Estimate  = tb[,1],
      SE        = tb[,2],
      Statistic = tb[,3],
      Pvalue    = tb[,4]
    )

  } else if(inherits(fit,"mle_dbsmoda")){

    mu <- fit$tables$mu
    phi <- fit$tables$phi

    out <- rbind(

      data.frame(
        Parameter=paste0("mu_",rownames(mu)),
        Estimate=mu[,1],
        SE=mu[,2],
        Statistic=mu[,3],
        Pvalue=mu[,4]
      ),

      data.frame(
        Parameter=paste0("phi_",rownames(phi)),
        Estimate=phi[,1],
        SE=phi[,2],
        Statistic=phi[,3],
        Pvalue=phi[,4]
      )
    )

  } else{

    beta <- fit$coefficients$beta

    out <- data.frame(
      Parameter=c(names(beta),"alpha"),
      Estimate=c(beta,fit$coefficients$alpha),
      SE=fit$se,
      Statistic=c(fit$zstat$beta,
                  fit$zstat$alpha),
      Pvalue=c(fit$pvalor$beta,
               fit$pvalor$alpha)
    )

  }

  out
}
```

```{r}
make_model_tables <- function(modelos,
                              folder = "C:\\Users\\07391760137\\Downloads\\Outros\\MSc-est\\SINAPE",
                              digits = 3){

  extract_results <- function(fit){

    if(inherits(fit,"mle_media")){

      tb <- fit$matcoef

      out <- data.frame(
        Parameter = rownames(tb),
        Estimate  = tb[,"Estimate"],
        SE        = tb[,"Std. Error"],
        Wald      = tb[,"t value"],
        Pvalue    = tb[,"Pr(>|t|)"],
        stringsAsFactors = FALSE
      )

    } else if(inherits(fit,"mle_dbsmoda")){

      mu  <- fit$tables$mu
      phi <- fit$tables$phi

      out <- rbind(

        data.frame(
          Parameter=paste0("mu_",rownames(mu)),
          Estimate =mu[,"Estimate"],
          SE       =mu[,"Std. Error"],
          Wald     =mu[,"t value"],
          Pvalue   =mu[,"Pr(>|t|)"],
          stringsAsFactors = FALSE
        ),

        data.frame(
          Parameter=paste0("phi_",rownames(phi)),
          Estimate =phi[,"Estimate"],
          SE       =phi[,"Std. Error"],
          Wald     =phi[,"t value"],
          Pvalue   =phi[,"Pr(>|t|)"],
          stringsAsFactors = FALSE
        )

      )

    } else if(inherits(fit,"bsreg.fit")){

      beta <- fit$coefficients$beta

      out <- data.frame(
        Parameter=c(names(beta),"alpha"),
        Estimate=c(beta,
                   fit$coefficients$alpha),
        SE=fit$se,
        Wald=c(fit$zstat$beta,
               fit$zstat$alpha),
        Pvalue=c(fit$pvalor$beta,
                 fit$pvalor$alpha),
        stringsAsFactors = FALSE
      )

    } else{

      stop("Unsupported model class.")

    }

    out

  }

  for(model_name in names(modelos)){

    fit <- modelos[[model_name]]

    tb <- extract_results(fit)

    header <- c(
      "\\begin{table}[ht]",
      "\\centering",
      paste0("\\caption{Parameter estimates for the ",model_name," regression model.}"),
      paste0("\\label{tab:",gsub(" ","_",tolower(model_name)),"}"),
      "\\begin{tabular}{lrrrr}",
      "\\toprule",
      "Parameter & Estimate & SE & Wald & $p$-value\\\\",
      "\\midrule"
    )

    body <- c()

    for(i in seq_len(nrow(tb))){

      body <- c(body,

        paste0(
          tb$Parameter[i],
          " & ",
          formatC(tb$Estimate[i],
                  digits=digits,
                  format="f"),
          " & ",
          formatC(tb$SE[i],
                  digits=digits,
                  format="f"),
          " & ",
          formatC(tb$Wald[i],
                  digits=digits,
                  format="f"),
          " & ",
          formatC(tb$Pvalue[i],
                  digits=digits,
                  format="f"),
          "\\\\"
        )

      )

    }

    footer <- c(
      "\\midrule",
      paste0("Log-likelihood & \\multicolumn{4}{r}{",
             formatC(fit$logLik,
                     digits=2,
                     format="f"),
             "}\\\\"),
      paste0("AIC & \\multicolumn{4}{r}{",
             formatC(fit$AIC,
                     digits=2,
                     format="f"),
             "}\\\\"),
      paste0("BIC & \\multicolumn{4}{r}{",
             formatC(fit$BIC,
                     digits=2,
                     format="f"),
             "}\\\\"),
      "\\bottomrule",
      "\\end{tabular}",
      "\\end{table}"
    )

    writeLines(
      c(header,
        body,
        footer),
      file.path(folder,
                paste0(gsub(" ","_",tolower(model_name)),
                       "_table.tex"))
    )

  }

  comparison <- c(
    "\\begin{table}[ht]",
    "\\centering",
    "\\caption{Model comparison according to the log-likelihood and information criteria.}",
    "\\label{tab:model_comparison}",
    "\\begin{tabular}{lrrr}",
    "\\toprule",
    "Model & Log-likelihood & AIC & BIC\\\\",
    "\\midrule"
  )

  for(model_name in names(modelos)){

    fit <- modelos[[model_name]]

    comparison <- c(
      comparison,
      paste0(
        model_name,
        " & ",
        formatC(fit$logLik,
                digits=2,
                format="f"),
        " & ",
        formatC(fit$AIC,
                digits=2,
                format="f"),
        " & ",
        formatC(fit$BIC,
                digits=2,
                format="f"),
        "\\\\"
      )
    )

  }

  comparison <- c(
    comparison,
    "\\bottomrule",
    "\\end{tabular}",
    "\\end{table}"
  )

  writeLines(
    comparison,
    file.path(folder,"model_comparison.tex")
  )

  cat("Tables successfully written.\n")

}

make_model_tables(modelos)
```

# Resíduos

```{r}
#| label: fun_envelope

## Extrai (escala, forma) da BS padrão implícitos em cada família de modelo,
## a partir da matriz de covariáveis x e (quando aplicável) do quantil q.
parametros_bs <- function(fit, x, model_type, q = NULL) {
  n <- nrow(x)
  switch(model_type,
    "media" = {
      list(scale = exp(as.vector(x %*% fit$beta)), shape = fit$alpha)
    },
    "moda" = {
      z <- matrix(1, nrow = n, ncol = 1)
      mu_i <- exp(as.vector(x %*% fit$beta_nu))
      phi  <- plogis(as.vector(z %*% fit$beta_xi))
      list(scale = mu_i / (1 - phi), shape = sqrt(phi))
    },
    "quantil" = {
      Q_i   <- exp(as.vector(x %*% fit$coefficients$beta))
      alpha <- fit$coefficients$alpha
      zq    <- qnorm(q)
      gma_alpha <- alpha * zq + sqrt(alpha^2 * zq^2 + 4)
      list(scale = 4 * Q_i / gma_alpha^2, shape = alpha)
    },
    stop("model_type desconhecido")
  )
}

## Resíduos de Cox-Snell generalizados a partir de (escala, forma) da BS
residuos_cs <- function(t, scale, shape) {
  xi <- (1 / shape) * (sqrt(t / scale) - sqrt(scale / t))
  S  <- 1 - pnorm(xi)
  -log(S)
}

## Reajusta o modelo correspondente para uma amostra simulada
refit_bs <- function(tsim, x, model_type, q = NULL) {
  switch(model_type,
    "media"   = mle_unc(x = x, t = tsim),
    "moda"    = mle_dbsmoda(x = x, z = matrix(1, nrow = nrow(x), ncol = 1), t = tsim),
    "quantil" = bsreg.fit(x = x, y = tsim, q = q, link = "log"),
    stop("model_type desconhecido")
  )
}

## Gera o envelope simulado (banda de confiança) para os resíduos de Cox-Snell
gerar_envelope <- function(fit, x, t, model_type, q = NULL, B = 100, conf = 0.95, seed = 2024) {
  set.seed(seed)
  n <- nrow(x)

  par_obs <- parametros_bs(fit, x, model_type, q)
  cs_obs  <- sort(residuos_cs(t, par_obs$scale, par_obs$shape))

  sim_mat <- matrix(NA_real_, nrow = 0, ncol = n)
  tentativas <- 0
  while (nrow(sim_mat) < B && tentativas < 5 * B) {
    tentativas <- tentativas + 1
    tsim  <- rbisa(n, shape = par_obs$shape, scale = par_obs$scale)
    fit_b <- tryCatch(refit_bs(tsim, x, model_type, q), error = function(e) NULL)
    if (is.null(fit_b)) next
    par_b <- tryCatch(parametros_bs(fit_b, x, model_type, q), error = function(e) NULL)
    if (is.null(par_b)) next
    res_b <- tryCatch(sort(residuos_cs(tsim, par_b$scale, par_b$shape)), error = function(e) NULL)
    if (is.null(res_b) || any(!is.finite(res_b))) next
    sim_mat <- rbind(sim_mat, res_b)
  }

  alpha_env <- 1 - conf
  lower     <- apply(sim_mat, 2, quantile, probs = alpha_env / 2, na.rm = TRUE)
  upper     <- apply(sim_mat, 2, quantile, probs = 1 - alpha_env / 2, na.rm = TRUE)
  media_sim <- apply(sim_mat, 2, mean, na.rm = TRUE)

  list(
    theoretical = qexp(ppoints(n)),
    observed    = cs_obs,
    lower       = lower,
    upper       = upper,
    mean        = media_sim,
    B_efetivo   = nrow(sim_mat)
  )
}

## Desenha (e opcionalmente salva) o gráfico envelope
plot_envelope <- function(env, main = "", file = NULL, width = 800, height = 600, res = 120) {
  if (!is.null(file)) png(file, width = width, height = height, res = res)
  ylim <- range(c(env$lower, env$upper, env$observed))
  plot(env$theoretical, env$observed,
       xlab = "Quantis teóricos Exp(1)",
       ylab = "Resíduos de CSG",
       main = main, pch = 16, ylim = ylim)
  polygon(c(env$theoretical, rev(env$theoretical)),
          c(env$upper, rev(env$lower)),
          col = adjustcolor("grey70", alpha.f = 0.5), border = NA)
  lines(env$theoretical, env$mean, col = "blue", lty = 2)
  points(env$theoretical, env$observed, pch = 16)
  abline(0, 1, col = "red")
  if (!is.null(file)) dev.off()
}

# residuos ajustados vs fitted values
plot_residuals_vs_fitted <- function(fit, x, t, model_type, q = NULL, file = NULL, width = 800, height = 600, res = 120) {
  par_obs <- parametros_bs(fit, x, model_type, q)
  cs_obs  <- residuos_cs(t, par_obs$scale, par_obs$shape)
  fitted_values <- par_obs$scale
  if (!is.null(file)) png(file, width = width, height = height, res = res)
  plot(fitted_values, cs_obs,
       xlab = "Valores ajustados",
       ylab = "Resíduos de CSG",
       main = "",
       pch = 16)
  abline(h = 0, col = "red")
  if (!is.null(file)) dev.off()
}

plot_hist <- function(t, main = "", file = NULL,
                      width = 800, height = 600, res = 120) {

  if (!is.null(file))
    png(file, width = width, height = height, res = res)

  hist(t,
       prob = TRUE,
       xlab = "Tempo até germinação (dias)",
       ylab = "Densidade",
       main = main,
       cex.axis = 1,
       cex.lab = 1,
       cex.main = 1)

  lines(density(t), lwd = 1.5)

  if (!is.null(file))
    dev.off()
}
```

```{r}
#| label: envelopes_aplicacao

#histograma + densidade t

t <- castor$time
x <- model.matrix(~ temperature + puncture + time_under_hydration, data = castor)
caminho_img <- "C:\\Users\\07391760137\\Downloads\\Outros\\MSc-est\\SINAPE\\img\\"

plot_hist(t, main = "",
          file = paste0(caminho_img, "hist_y.png"))

# Média
env_media <- gerar_envelope(mle_media, x, t, model_type = "media", B = 100)
plot_envelope(env_media, main = "",
              file = paste0(caminho_img, "envelope_media.png"))
plot_residuals_vs_fitted(mle_media, x, t, model_type = "media",
                           file = paste0(caminho_img, "residuals_vs_fitted_media.png"))

# Moda
env_moda <- gerar_envelope(mle_moda, x, t, model_type = "moda", B = 100)
plot_envelope(env_moda, main = "",
              file = paste0(caminho_img, "envelope_moda.png"))
plot_residuals_vs_fitted(mle_moda, x, t, model_type = "moda",
              file = paste0(caminho_img, "residuals_vs_fitted_moda.png"))

# Quantil 10%
env_q10 <- gerar_envelope(mle_quantil_10, x, t, model_type = "quantil", q = 0.1, B = 100)
plot_envelope(env_q10, main = "",
              file = paste0(caminho_img, "envelope_quantil_10.png"))
plot_residuals_vs_fitted(mle_quantil_10, x, t, model_type = "quantil", q = 0.1,
              file = paste0(caminho_img, "residuals_vs_fitted_quantil_10.png"))
# Mediana
env_mediana <- gerar_envelope(mle_mediana, x, t, model_type = "quantil", q = 0.5, B = 100)
plot_envelope(env_mediana, main = "",
              file = paste0(caminho_img, "envelope_mediana.png"))
plot_residuals_vs_fitted(mle_mediana, x, t, model_type = "quantil", q = 0.5,
              file = paste0(caminho_img, "residuals_vs_fitted_mediana.png"))
# Quantil 90%
env_q90 <- gerar_envelope(mle_quantil_90, x, t, model_type = "quantil", q = 0.9, B = 100)
plot_envelope(env_q90, main = "",
              file = paste0(caminho_img, "envelope_quantil_90.png"))
plot_residuals_vs_fitted(mle_quantil_90, x, t, model_type = "quantil", q = 0.9,
              file = paste0(caminho_img, "residuals_vs_fitted_quantil_90.png"))
```
