---
title: "Lista 1"
subtitle: "Estatística Matemática"
author: "Tailine J. S. Nonato"
date: today
date-format: long
format: html
---

## Exercício 1
Se $\Omega = \{C, R\} \times \{C, R\}$, determine o conjunto potência $P(\Omega)$.

### Resolução

\begin{align*}
\mathcal{P}(\Omega) &= \{\emptyset, \Omega, \{(C,C)\}, \{(C,R)\}, \{(R,C)\}, \{(R,R)\}, \\
&\{(C,C),(C,R)\}, \{(C,C),(R,C)\}, \{(C,C),(R,R)\}, \\
&\{(C,R),(R,C)\}, \{(C,R),(R,R)\}, \{(R,C),(R,R)\}, \\
&\{(C,C),(C,R),(R,C)\}, \{(C,C),(C,R),(R,R)\}, \\
&\{(C,C),(R,C),(R,R)\}, \{(C,R),(R,C),(R,R)\} \}
\end{align*}

O número de subconjuntos de um conjunto com $n$ elementos é $2^n$. Assim, o número de subconjuntos de $\Omega$ é $2^4=16$.

## Exercício 2
Se $\mathcal{F}$ é uma $\sigma$-álgebra, verifique que:

(a) Se $\{A_i\}_{i=1}^n \subset \mathcal{F}$ então $\bigcup_{i=1}^n A_i \in \mathcal{F}$ e $\bigcap_{i=1}^n A_i \in \mathcal{F}$.

(b) Se $\{A_i\}_{i=1}^\infty \subset \mathcal{F}$ então $\bigcap_{i=1}^\infty A_i \in \mathcal{F}$.

(c) $A, B \in \mathcal{F}$ então $A \cap B^c \in \mathcal{F}$.

### Resolução

(a) 

Dado que $\mathcal{F}$ é uma $\sigma$-álgebra, tem-se que:

Pela definição de $\sigma$-álgebra, $\mathcal{F}$ é fechada sob união finita e interseção finita. Assim, se $A_i \in \mathcal{F}$ para todo $i=1,\ldots,n$, então:
 
$\bigcup_{i=1}^n A_i \in \mathcal{F}$ e $\bigcap_{i=1}^n A_i \in \mathcal{F}$.

(b)

 Dado que $\mathcal{F}$ é uma $\sigma$-álgebra, tem-se que:

 Assim como no item (a), tem-se pela definição que $\mathcal{F}$ é fechada sob união infinita e interseção infinita. Assim, se $A_i \in \mathcal{F}$ para todo $i=1,\ldots,\infty$, então:

 $\bigcap_{i=1}^\infty A_i \in \mathcal{F}$.

 (c)

  Dado que $\mathcal{F}$ é uma $\sigma$-álgebra, tem-se que:

 Pela definição de $\sigma$-álgebra, $\mathcal{F}$ é fechada sob complemento. 
 
 Assim, se $A, B \in \mathcal{F}$, então $B^c \in \mathcal{F}$. 
 
 Portanto, como $\mathcal{F}$ é fechada sob interseção finita, tem-se que:

 $A \cap B^c \in \mathcal{F}$.

## Exercício 3
Seja $I$ um conjunto de índices. Verifique que: se $\{\mathcal{F}_i\}_{i\in I}$ é uma família de $\sigma$-álgebras, então $\bigcap_{i\in I}\mathcal{F}_i$ é uma $\sigma$-álgebra.

### Resolução


## Exercício 4
Considere $\Omega = \{a, b, c\}$ e as coleções $\mathcal{F}_1 = \{0, \Omega, \{a\}, \{b, c\}\}$ e $\mathcal{F}_2 = \{0, \Omega, \{c\}, \{a, b\}\}$. As coleções $\mathcal{F}_1$ e $\mathcal{F}_2$ são $\sigma$-álgebras? $\mathcal{F}_1 \cup \mathcal{F}_2$ é uma $\sigma$-álgebra?

**Resposta:** (a) Sim, (b) Não.

## Exercício 5
Sejam $\Omega = \{1, 2, 3, 4, 5, 6\}$, $A =$ "o resultado é um número par" e $B = A - \{6\}$. Encontre as $\sigma$-álgebras $\sigma(\{A\})$ e $\sigma(\{A, B\})$, e as compare.

## Exercício 6
Obtenha a $\sigma$-álgebra gerada pela classe $\mathcal{C} = \{0, 1\}, \{1, 2\}$ se:

(a) $\Omega = \{0, 1, 2\}$.

(b) $\Omega = \{0, 1, 2, 3\}$.

## Exercício 7
Obtenha a $\sigma$-álgebra de $\Omega = \{1, 2, 3, 4, 5\}$ gerada por:

(a) $\mathcal{C}_1 = \{\{2\}\}$.

(b) $\mathcal{C}_2 = \{\{1, 2\}\}$.

(c) $\mathcal{C}_3 = \{\{1, 2, 3\}\}$.

(d) $\mathcal{C}_4 = \{\{1, 2\}, \{1, 3\}\}$.

(e) $\mathcal{C}_5 = \{\{1\}, \{2, 3\}\}$.

### Resolução

(a) $\mathcal{F}_1 = \{\emptyset, \Omega, \{2\}, \{1, 3, 4, 5\}\}$

(b) $\mathcal{F}_2 = \{\emptyset, \Omega, \{1, 2\}, \{3, 4, 5\}\}$

(c) $\mathcal{F}_3 = \{\emptyset, \Omega, \{1, 2, 3\}, \{4, 5\}\}$

(d) $\mathcal{F}_4 = \{\emptyset, \Omega, \{1, 2\}, \{1, 3\}, \{3, 4, 5\}, \{2, 4, 5\}, \{1, 2,3 \} \{4, 5\}\}$

(e) $\mathcal{F}_5 = \{\emptyset, \Omega, \{1\}, \{2, 3\}, \{2, 3 , 4, 5\}, \{1, 4, 5\} \{1, 2, 3\}, \{4, 5\}\}$

## Exercício 8
Construa a menor $\sigma$-álgebra em $[0,1]$, contendo o subconjunto $[1/4,3/4]$.

## Exercício 9
Sejam $A_{1},A_{2},\ldots$ eventos aleatórios. Verifique que:

(a) $\mathbb{P}\Big{(}\bigcap_{k=1}^{n}A_{k}\Big{)}\geqslant 1-\sum_{k=1}^{n}\mathbb{P}(A_{k}^{\varepsilon})$.

(b) Se $\mathbb{P}(A_{k})\geqslant 1-\varepsilon$ para $k=1,\ldots,n\in\varepsilon>0$, então $\mathbb{P}\Big{(}\bigcap_{k=1}^{n}A_{k}\Big{)}\geqslant 1-ne$.

(c) $\mathbb{P}\Big{(}\bigcap_{k=1}^{\infty}A_{k}\Big{)}\geqslant 1-\sum_{k=1}^{\infty}\mathbb{P}(A_{k}^{\varepsilon})$.

**Resposta:** (a) Use a sub-aditividade de $\mathbb{P}$, (b) Use o Item (a), (c) Use a sub-aditividade de $\mathbb{P}$.

## Exercício 10
Verifique as seguintes propriedades:

(a) Se $\mathbb{P}(A_{n})=0$ para $n=1,2,\ldots$, então $\mathbb{P}\Big{(}\bigcup_{n=1}^{\infty}A_{n}\Big{)}=0$.

(b) Se $\mathbb{P}(A_{n})=1$ para $n=1,2,\ldots$, então $\mathbb{P}\Big{(}\bigcap_{n=1}^{\infty}A_{n}\Big{)}=1$.

**Resposta:** Para (a) e (b) use a sub-aditividade de $\mathbb{P}$.

## Exercício 11
Um casal é escolhido ao acaso e o número de filhos e filhas perguntado. Considerando o evento $A=\text{``um casal não tem filhos''}\in\mathbb{P}(\{\omega\})=1/2^{x+y+2}$ para todo $\omega=(x,y)\in\Omega$, determine $\mathbb{P}(A)$.

**Resposta:** $1/2$.

## Exercício 12
Uma moeda é lançada $n$ vezes, $n\geqslant 2$. Qual é a probabilidade de que, nestes $n$ lançamentos, não apareçam $2$ caras seguidas?

**Resposta:** $\frac{{n\choose 2}+2}{2^{n}}$.

---

## Notação de Conjuntos
Seja $\{A_{i}\}_{i=1}^{\infty}\subset\mathscr{F}$. Denotamos:

(I) $A_{n}\uparrow A\iff A_{n}\subset A_{n+1}\ \forall n\geqslant 1\ \in\bigcup_{i=1}^{\infty}A_{i}=A$.

(II) $A_{n}\downarrow A\iff A_{n+1}\subset A_{n}\ \forall n\geqslant 1\ \in\bigcap_{i=1}^{\infty}A_{i}=A$.

(III) $\limsup_{n\to\infty}A_{n}\stackrel{{\mathrm{def.}}}{{:=}}\bigcap_{n=1}^{\infty}\bigcup_{m=n}^{\infty}A_{m}$.

(IV) $\liminf_{n\to\infty}A_{n}\stackrel{{\mathrm{def.}}}{{:=}}\bigcup_{n=1}^{\infty}\bigcap_{m=n}^{\infty}A_{m}$.

(V) $A_{n}\to A\iff\limsup_{n\to\infty}A_{n}=\liminf_{n\to\infty}A_{n}=A$.
---

## Exercício 13
Seja $\{A_{i}\}_{i=1}^{\infty}\subset\mathscr{F}$. Verifique que:

(a) Se $A_{n}\uparrow A$ então $\lim_{n\to\infty}\mathbb{P}(A_{n})=\mathbb{P}(A)\in\mathbb{P}(A_{n})\leqslant \mathbb{P}(A_{n+1})\ \forall n\geqslant 1$.

(b) Se $A_{n}\downarrow A$ então $\lim_{n\to\infty}\mathbb{P}(A_{n})=\mathbb{P}(A)\in\mathbb{P}(A_{n})\geqslant \mathbb{P}(A_{n+1})\ \forall n\geqslant 1$.

(c) Se $A_{n}\to A$ então $A\in\mathscr{F}\in\lim_{n\to\infty}\mathbb{P}(A_{n})=\mathbb{P}(A)$.

(d) Se $\sum_{i=1}^{\infty}\mathbb{P}(A_{i})<\infty$ então $\mathbb{P}\big{(}\limsup_{n\to\infty}A_{n}\big{)}=0$.

**Resposta:** (a) Escreva $A_n$ e $A$ como união disjunta de eventos e aplique a $\sigma$-aditividade de $\mathbb{P}$,

(b) Use o Item (a),

(c) Use os Itens (a) e (b),

(d) Use a sub-aditividade de $\mathbb{P}$ e o fato de que \[ \lim_{n \to \infty} \sum_{i=n}^{\infty} \mathbb{P}(A_i) = 0. \]

## Exercício 14
Se $A, B, C \in \mathcal{F}$, verifique que:

\[ \mathbb{P}(A \cup B \cup C) = \mathbb{P}(A) + \mathbb{P}(B) + \mathbb{P}(C) - \mathbb{P}(A \cap B) - \mathbb{P}(A \cap C) - \mathbb{P}(B \cap C) + \mathbb{P}(A \cap B \cap C). \]

## Exercício 15
Verifique que a aplicação $A \mapsto \mathbb{P}(A|B)$ é uma medida de probabilidade.

## Exercício 16
Certo experimento consiste em lançar um dado equilibrado 2 vezes, independentemente. Dado que os dois números sejam diferentes, qual é a probabilidade de:

(a) Pelo menos um dos números ser 6?

(b) A soma dos números ser 8?

**Resposta:** (a) 1/3, (b) 2/15.

## Exercício 17
Verifique que:

(a) Um evento $A$ com $\mathbb{P}(A) = 0$ é independente a qualquer outro evento $B$.

(b) Um evento $A$ com $\mathbb{P}(A) = 1$ é independente a qualquer outro evento $B$.

## Exercício 18
Considere o circuito em série da figura abaixo, onde $R_1$ e $R_2$ são componentes eletrônicos idênticos que permitem a passagem de corrente elétrica, cuja probabilidade da corrente perpassar cada um é $p$. Determine a probabilidade da corrente sair de $A$ e chegar a $B$.


**Resposta:** $p^2$.

## Exercício 19
Sejam $A_1, \ldots, A_n$ eventos aleatórios independentes, com $\mathbb{P}(A_k) = p_k, k = 1, \ldots, n$. Obtenha a probabilidade de ocorrência dos seguintes eventos, em termos das probabilidades $p_k$:

(a) A ocorrência de nenhum dos $A_k$.

(b) A ocorrência de pelo menos um dos $A_k$.

(c) A ocorrência de exatamente um dos $A_k$.

(d) A ocorrência de exatamente dois dos $A_k$.

(e) A ocorrência de todos os $A_k$.

(f) A ocorrência de, no máximo, $n - 1$ dos $A_k$.

**Resposta:** (a) $\prod_{k=1}^{n} (1 - p_k)$,  
(b) $1 - \prod_{k=1}^{n} (1 - p_k)$,  
(c) $\sum_{i=1}^{n} p_i \prod_{k \neq i} (1 - p_k)$,  
(d) $\sum_{i<j} p_i p_j \prod_{k \neq i,j} (1 - p_k)$,  
(e) $\prod_{k=1}^{n} p_k$,  
(f) $1 - \prod_{k=1}^{n} p_k$.

## Exercício 20
Sejam $A, B, C$ eventos definidos na figura

(a) Os eventos $A$ e $C$ são independentes?  
(b) Os eventos $A$ e $B$ são independentes?

**Resposta:** (a) Sim, (b) Não.

## Exercício 21
Sejam $A_1, A_2, \ldots, A_n$ e $B_1, B_2, \ldots, B_n$ eventos definidos em $(\Omega, \mathcal{F}, \mathbb{P})$. Para $j = 1, 2, \ldots, n$ suponha que $B_j$ seja independente de $\bigcap_{i=1}^n A_i$ e que os $B_j$'s sejam disjuntos 2 a 2. Os eventos $\bigcup_{j=1}^n B_j$ e $\bigcap_{i=1}^n A_i$ são independentes?

**Resposta:** Sim.

## Exercício 22
Seja $\Omega = \{abc, acb, cab, cba, bca, bac, aaa, bbb, ccc\}$ com $\mathbb{P}(\{\omega\}) = 1/9$ para todo $\omega \in \Omega$, e o evento $A_k = k$-ésima letra é $a$, $k = 1, 2, 3$. Verifique que a família $\{A_1, A_2, A_3\}$ é 2 a 2 independente porém não independente (coletivamente).

## Exercício 23
Os coeficientes $a$ e $b$ da equação $ax^2 + bx + 1 = 0$ são, respectivamente, os resultados sucessivos de 2 lançamentos de um dado equilibrado. Determine a probabilidade das raízes dessa equação serem números reais.

**Resposta:** 19/36.

## Exercício 24
Assuma que para cada cliente que solicita o cancelamento de um plano, a companhia responsável o faça com probabilidade $q$.

(a) Se 4 clientes solicitam o cancelamento, qual a probabilidade de que a companhia cancele o plano de exatamente 2 clientes?

(b) Qual a probabilidade de que sejam necessários exatamente 10 solicitações negadas para que o primeiro cancelamento seja efetuado?

**Resposta:** (a) $6q^2(1 - q)^2$, (b) $(1 - q)^{10}q$.

## Exercício 25
Numa população 10% das pessoas são infectadas por um determinado vírus. Um teste para detecção do vírus é eficiente em 95% dos casos nos quais os indivíduos são infectados, mas resulta em 4% de resultados positivos para os não infectados. Qual a probabilidade de que o teste de uma pessoa dessa população dê resultado positivo?

**Resposta:** 0.131.

## Exercício 26
Suponha que temos duas urnas: a primeira tem 4 bolas azuis e 6 bolas brancas, a outra tem 7 azuis e 3 brancas. Lançamos um dado honesto, se sair um número par, selecionamos ao acaso uma bola da primeira urna, se for um número ímpar da segunda. Qual a probabilidade de selecionar uma bola azul?

**Resposta:** 0.55.

## Exercício 27
Considere uma urna que contem 1 bola vermelha, 4 bolas brancas e 3 azuis. Supondo que se efetuam extrações sem reposição de 2 bolas, determine a probabilidade de retirar 1 bola vermelha na segunda extração.

**Resposta:** 0.125.

## Exercício 28
Um lote contém 15 peças, de onde 5 são defeituosas. Se um funcionário extrai uma amostra de 5 peças aleatoriamente:

(a) Qual é a probabilidade de que a amostra não contenha peças defeituosas se a escolha foi realizada com reposição?

(b) Qual é a probabilidade de que a amostra não contenha peças defeituosas, se a escolha foi realizada sem reposição?

**Resposta:** (a) 0.1317, (b) 0.0839.

## Exercício 29
Suponha que a ocorrência de chuva (ou não) dependa das condições do tempo do dia anterior. Assumamos que, se (não) chova hoje, choverá amanhã com probabilidade (respectivamente q) p. Sabendo que choveu hoje, calcule a probabilidade de chover depois de amanhã.

**Resposta:** $p^2 + q(1 - p)$.

```{r}
sample(c(1:29), 1)
```